name: Interview Preparation palcu.ro
description: Cracking the coding interview
meta_description: "Alex Palcuie's blog for cracking the coding interview"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /

# Details for the RSS feed generator
url:            'http://interviews.palcu.ro'
author:         'Alex Palcuie'
authorTwitter:  'AlexPalcuie'

permalink:       /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems:
  - jekyll-feed
